### ISSUE TITLE
Expose module version as part of startup logs and instrumentationScope

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1000]
**Description**

**Criterias**
- There is a place in the repository holding the current module version. On main it is main, on a release branch it is the actual version.
- Optional a PR could have the PR-number as version
- Optional the development release has a -dev suffix in the version
- That version gets printed as part of the startup logs
- That version is placed into the instrumentationScope.version whenever an instrumentationScope.name is set by our code

**Reasons**
The instrumentationScope is a basic attribute in OTEL and should be filled always in a proper way. User can relate the metric spec from the version number.

**Attachments**

**Release Notes**

```

```

**Comment by chrkl** [comment]
The module version was added on code level, which is logged during the operator startup and added to the instrumentation scope. The version has to be updated before a release.

We keep this issue open to also automate setting the version during the build.
