### ISSUE TITLE
Merge env and e2e tests

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1020]
**Description**
For the telemetry-manager there are 3 different kind of test realized: unit test, env test, e2e test
It is hard to grasp when to write an env test and when to write an e2e test. ALso the used technology is different (one is a full integration test while the other mocks an apiserver)
To keep it simple, the team decided to remove the middle test layer.

**Criterias**
- Unit tests are not starting an APIServer anymore
- Installing env test binary is removed from make targets
- No loss in test coverage
- The test strategy document is updated to reflect the change (https://github.com/kyma-project/telemetry-manager/blob/main/docs/contributor/testing.md)

**Comment by shorim** [comment]
TODO list:

- [ ] Migrate env tests for Telemetry controller https://github.com/kyma-project/telemetry-manager/pull/1031
- [ ] Migrate env tests for TracePipeline and MetricPipeline controllers 
       - https://github.com/kyma-project/telemetry-manager/pull/1057
       - https://github.com/kyma-project/telemetry-manager/pull/1062
       - https://github.com/kyma-project/telemetry-manager/pull/1063
- [ ] Migrate env tests for LogPipeline and LogParser controllers
- [ ] Remove env tests from test strategy documentation and remove env test binary dependency from Makefile
