### ISSUE TITLE
Have a test for multiple LogPipelines

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1021]
**Description**
Usually, the log domain is used by running multiple pipelines (app logs and acces logs) but there is no integration tests assuring the parallel operation of such.

**Criterias**
- Have a test for multiple LogPipelines similar to Traces and Metrics

**Comment by hisarbalik** [comment]
New e2e test scenarios for log pipeline added:
- Removed include and exclude namespace filter e2e test
- Add include and exclude namespace filter e2e tests with multi log pipeline scenarios
- Add max log pipeline e2e test
- Add basic multi log pipeline e2e test
- Add broken multi log pipeline e2e test
- Refactor existing metric and trace multi pipeline e2e tests
