### ISSUE TITLE
Validate OTLP Endpoint

### ISSUE THREAD

**Issue by chrkl** [kyma-project/telemetry-manager#1106]
**Description**

[Recent changes](https://github.com/open-telemetry/opentelemetry-collector/issues/9505) to the OpenTelemetry collector may terminate the Collector ungracefully in the case of a malformed OTLP endpoint. 

**Expected result**

An endpoint value in a MetricPipeline or TracePipeline should never result in a crashing Pod. If the user defines a value that will not be accepted by the Collector, the configuration should not be applied and the problem indicated in the pipeline status.

Ensure that pipeline validation logic is not duplicated in the individual reconcilers

**Actual result**

When a user defines such an endpoint in a MetricPipeline or TracePipeline, this results in a crashing pod. In older releases of the Collector, it was running but not shipping any data.

**Steps to reproduce**

Create a MetricPipeline with endpoint that does not have a port. E.g., set the value to `/`. The exact values that are accepted by the Collector have to be evaluated.

**Troubleshooting**

**Release Notes**

```

```
 Similar but different ticket: https://github.com/kyma-project/telemetry-manager/issues/1106

**Comment by k15r** [comment]
actually quite the opposite: 
if we prevent setting invalid values in the CR using x-validation, then existing pipelines will still (not) work as before. If we introduce a change in the reconciliation mechanism, then we have to introduce a new condition on the CR to transport this information to the user.

**Comment by TeodorSAP** [comment]
Endpoint validation improved, with different scenarios for OTLP: HTTP and GRPC protocols and Fluentd: HTTP, port validation, schema validation, etc. UTs and E2E tests were also improved to test as many scenarios as possible.
