### ISSUE TITLE
Enhance runtime input with k8sclusterreciver metrics

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1184]
**Description**
As part of https://github.com/kyma-project/telemetry-manager/issues/972 enhance the current runtime input with metrics provided by k8sclusterreceiver

**Criterias**
- The metrics for pods and containers are enhanced with additional metrics as outlined in https://github.com/kyma-project/telemetry-manager/issues/1001#issuecomment-2154182359
- The new metrics are based on the k8sclusterreicever being wrapped with the leader-election-receiver

**Tasks**
- Use new otel-collector distro
- the runtime input generates a k8sclusterreiceiver receiver, selecting the metrics matching the resource selector of the input (RBAC changes needed)
- The k8sclusterreiceiver is wrapped by a singletonreceivercreator (RBAC changes needed)
- Enhance documentation
- Enhance E2E test for runtime input (to assure compatibility of the emmitted metrics)
- Come to a decision if new metrics can be added for existing cluster (check the amount of new metrics/labels added per container)
- Implement decision results and remove feature flag 

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by skhalash** [comment]
First step:
* Enhance kubeletstatsreceiver metrics for pods/containers with k8sclusterreceiver metrics
* Hide this change behind a feature flags, we don't want to roll it out to the users before there is a way to exclude metrics

**Comment by rakesh-garimella** [comment]
The feature has been implemented without feature flag. Currently a total of 5 new metrics have been exposed when `runtime` is enabled on metricpipeline
