### ISSUE TITLE
Fix flaky E2E tests

### ISSUE THREAD

**Issue by skhalash** [kyma-project/telemetry-manager#1253]
**Description**

There has been a certain degradation in E2E test stability, we need to address it:
* "Telemetry pipelines is not running" happening sporadically in various test suites, logging has to be improved (for example, https://github.com/kyma-project/telemetry-manager/actions/runs/9600295514/job/26489915753)
* Self-monitor negative tests failing from time to time when updating the Telemetry resource (for example, https://github.com/kyma-project/telemetry-manager/actions/runs/9843544682/job/27174973694?pr=1241)
* Gardener tests are not stable

* to better understand the reasons for failing tests, the test output must be improved:
  https://github.com/kyma-project/telemetry-manager/pull/1288

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Release Notes**

```

```

**Comment by k15r** [comment]
Closing as discussed. New issues with more actionable requirements will be opened.
