### ISSUE TITLE
[OTLP Log] Gateway performance evaluation

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1289]
**Description**
In order to go with the targetted architecture as outlined in https://github.com/kyma-project/telemetry-manager/issues/556, it is crucial to understand if bigger cluster setups can be realized even without having an auto scaling of the gateway in place. If that is not the case, an alternative setup might be possible where the agent is encompassing the all gateway logic additional and pushs directly to the target.

**Goal**
Understand how much a typical gateway setup can handle, assuming the ideal backend. Is the performance that well already, that anyway backends cannot handle this high volume of logs?

**Criterias**
- High log volume tests are executed with a two replica gateway setup doing similar logic as in the metric gateway
- Results are documented as well as conclusions on if a non-auto-scaling gateway setup is tolerable for the MVP

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by k15r** [comment]
Come up with a sizing definition for a single gateway instance:
- needs to be able to handle the maximum load accepted by a "regular" CLS instance
- use the same `log` definition as used by CLS

- Push logs using telemetrygen

**Comment by k15r** [comment]
https://github.com/kyma-project/telemetry-manager/pull/1318
