### ISSUE TITLE
Enhance runtime input with selectors for PVC volumes

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1301]
**Description**
As part of https://github.com/kyma-project/telemetry-manager/issues/972 enhance the current runtime input with a new selector for volumes. It should be disabled by default.

**Criterias**
- A new selector is added to the runtime input which will emit metrics as outlined in https://github.com/kyma-project/telemetry-manager/issues/1001#issuecomment-2154182359
- The selector can be used independent of the other selectors, if this selector is enabled only, only the related metrics are exported
- The new metrics are based on the existing k8sclusterreicever being wrapped with the leader-election-receiver
- Multiple pipelines having different selector settings will result in different metrics being exported
- Assure that only metrics for volumes being attached to a PVC are exported. Other volumes should be filtered out
- Check with the Cloud Manager team how much these metrics are useful for NFS volumes and decide if they should be included or excluded
- The k8sclusterreicever is running at the agent instead of gateway as it is representing an optional input
- There is no runtime instrumentation scope processor in the gateway

**Tasks**
- Add new feature with filter for PVC volumes
- Align with cloud manager about NFC volumes
- Verify proper instrumentation scope is in use
- Enhance documentation
- Enhance E2E test for runtime input (to assure compatibility of the emmitted metrics)

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by rakesh-garimella** [comment]
The changes wrt to volume metrics has been implemented and also the k8sCluster has been moved to metric agent
