### ISSUE TITLE
Update to otel-collector 0.107.0

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1357]
**Description**
OTEL version 0.106 adds the new metric attribute `data_type` to `otelcol_exporter_queue_size`, this will cause empty results for arithmetic queries such as alert rule *QueueAlmostFull rules. The reason is that the queries in this operation no longer have identical label pairs (`otelcol_exporter_queue_size` got a new attribute but not another metric `otelcol_exporter_queue_capacity`). For more details read [this](https://prometheus.io/docs/prometheus/latest/querying/operators/#vector-matching) document.

OTEL component names are now restricted to the 63 character length this causes issues with the filter name  `filter/metrics-prometheus-input-diagnostic-metric-filter-by-namespace-prometheus-input`, there is a fix for this issue but not part of patch release 0.106.1 https://github.com/open-telemetry/opentelemetry-collector/pull/10818

**Tasks**
- otelcol_exporter_queue_size problem
  - Rewrite internal alert rules for operations
  - Rewrite alert rules of self-monitor
- Verify fix for plugin name length
- API update
  - Update own components to the new API version (API breaking changes happened), see example [here](https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/34234/files) similar to `sigletonreceivercreator` imlementation
  - Update own components to new metric prefixes
- Update to the new binary collector version

Dependabot version bump PR https://github.com/kyma-project/opentelemetry-collector-components/pull/106

**Comment by hisarbalik** [comment]
- OTel image version bumped to 0.107.0
- Component scope names updated from the [list](https://github.com/open-telemetry/opentelemetry-collector-contrib/releases/tag/v0.107.0)
- Feature gate argument `confmap.unifyEnvVarExpansion` removed, this is now stable
- Update alert rule queries with `otelcol_exporter_queue_size` metrics, ignore new metric attribute `data_type` in arithmetic queries
- Bump telemetrygen images to version 0.107.0, update trace load test setup
- Add load test results for OTel image version 0.107.0
