### ISSUE TITLE
Understand the OTTL package and decide if it can be used as external interface

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1483]
**Description**
To get started with https://github.com/kyma-project/telemetry-manager/issues/1293, a decision must be taken on how the typical extended feature set of transform & filter across the signal types can be offered to the end user. Hereby, exposing the OTTL grammar sounds very promising, however brings quite some risks.

Benefits:
- Well defined language with documentation
- Supports all typical scenarios, no additional processors will be needed probably
- No need to understand a new language/custom abstraction

Risks:
- An update of the package version might break running pipelines by introducing unexpected syntax/semantic changes or bugs
- Troubleshooting for customers might be cumbersome when developing an expression, they might to read logs etc.

Questions to answer in this ticket:
- Can we support the language as input for filter & transform or must we have an own abstraction?
- Can we have the support limited to some basic elements?
- Can we validate expressions using the library directly, how big will be the coverage, are there still situations where you would need to read logs?
- When using a "unsupported" disclaimer to mitigate risk, on which levell that disclaimer will act (only some elements?)

**Comment by hisarbalik** [comment]
After discussion with OTTL community developers an ADR created.
