### ISSUE TITLE
New OTLP input for LogPipeline

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#1523]
**Description**
Relates to https://github.com/kyma-project/telemetry-manager/issues/556 and enables https://github.com/kyma-project/telemetry-manager/issues/872

Criterias:
- Have a new OTLP input available on the dev release only
- The new input can only be activated if there is an OTLP output
- The new input can be used in parallel with runtime input
- The new input can be used without runtime input, making the runtime input optional when used with OTLP output

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by k15r** [comment]
Implemented in #1542
