### ISSUE TITLE
Understand further the cache usage in controller runtime

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/telemetry-manager#196]
**Description**

We have restricted the cache usage in controller runtime with [PR](https://github.com/kyma-project/telemetry-manager/pull/93). however in some cases we still see high cache usage. When running pprof we se there 2 caches initialised on is within main and another cache. We should investigate why we get 2 caches ?

We should also try to restrict the cache such that we have an economic memory foot print for telemetry operator

**Steps to reproduce**

Run pprof on a running telemetry operator

**Comment by chrkl** [comment]
The topic has been investigated while working on https://github.com/kyma-project/telemetry-manager/issues/464. The operators memory usage is constant with https://github.com/kyma-project/telemetry-manager/issues/196.
