### ISSUE TITLE
Basic upgrade test

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#213]
**Description**

Introduce a basic upgrade test with a single test case as a base for further additions
Hereby the following questions should get answered:
- Test manager upgrade from last release to current revision
- Which test suite version to run (latest release or revision, splitted?)
- Can we re-use test cases? Setup, execute test, upgrade, execute same test?
- Use same test cases which we have already in e2e? If not, what the focus will be?
- Dedicated job?
- Dedicated folder?
- Local execution supported?
- Deployment based on lifecycle-manager

Criterias:
- On a new code revision the upgrade test gets executed automated against latest release
- test strategy document got enhanced

**Reasons**

**Attachments**

**Comment by ameteiko** [comment]
#### Which test suite version to run (latest release or revision, splitted?)

The test suite runs in two stages: 
1. It deploys the latest released operator version and runs the test suite for that particular revision.
2. It upgrades the telemetry operator to the recent version and runs the recent test suite over it.

#### Can we reuse test cases? Setup, execute a test, upgrade, run the same test?

The test suites used for the upgrade test are the cherry-picked test scenarios from the E2E test suite. The focus is on the high-level operability of the telemetry operator.

#### Use the same test cases that we already have in E2E? If not, what the focus will be?

The test scenarios in the upgrade test are the smoke-test suite that ensures that only the basic operability of the telemetry operator is provided. The rest of the validation is performed in the E2E test stage.

#### Dedicated job?

The dedicated ProwJob `pull-telemetry-manager-upgrade-test` is used for running the test suite during the building pipeline.

#### Dedicated folder?

There is no need for a dedicated folder for the test suite. All the E2E tests designated to run should be labelled as "operational" in the E2E test suite.

#### Local execution supported?

The local execution is supported with `make upgrade-test` target.

#### Deployment based on lifecycle-manager

The deployment doe not use the Lifecycle Manager. It is performed using the git tag for the latest release.

**Comment by a-thaler** [comment]
Thanks for the extended closing comments :)
