### ISSUE TITLE
Review the microwebsite for Telemetry module

### ISSUE THREAD

**Issue by NHingerl** [kyma-project/telemetry-manager#271]
**Description**

Check whether the microwebsite for the Telemetry module looks good and works fine:

https://docs.kyma-project.io//?basePath=https://raw.githubusercontent.com/kyma-project/telemetry-manager/main/&homepage=docs/user/README.md&sidebar=true&loadSidebar=docs/user/_sidebar.md&browser-tab-title=Telemetry%20module%20documentation#/docs/user/README

- known issue: relative links don't work; will have to update them. => https://github.com/kyma-project/telemetry-manager/pull/275
- any other issues?

**Area**

* Telemetry

**Reasons**

When the Telemetry module goes live, the website is going to be the link target in the [Kyma modules](https://kyma-project.io/docs/kyma/latest/01-overview/#kyma-modules) table on kyma-project.io.

**Assignees**

**Attachments**

**Comment by hisarbalik** [comment]
Some review comments:

- On the page `Tracing` in `Step 5` section `Basic authentication` not well rendered wenn expanded
- Same as above `in section `Istio` when `Set up extension provider` expanded rendered not well

**Comment by NHingerl** [comment]
Hi @hisarbalik, thank you for noticing this! I fixed the rendering issues.
