### ISSUE TITLE
Basic istio access logs test

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#288]
**Description**
Start realizing the concept outlined in https://github.com/kyma-project/telemetry-manager/issues/261 by introducing a first istio based E2E test. The test should bring an istiofied sample application serving a simple GET API to be called. After activating access logs via the istio telemetry API, access logs should start arriving at the mock backend and the agreed access log format can be verified.

**Tasks**
- rename existing test suite to the proposed new naming
- extract the testkit to be used by the component and e2e test suite
- install the istio module latest release
- configure istio telemetry and LogPipeline
- deploy sample app and call GET endpoint
- verify access logs in the backend
- Automate it as PR based CI job

**Criterias**
Test in an automated way that the istio access log functionality is working as expected using latest istio module

**Reasons**

**Attachments**

**Comment by rakesh-garimella** [comment]
The test has been implemented along with prow jobs.
