### ISSUE TITLE
Fluent Bit stops with SIGSEGV

### ISSUE THREAD

**Issue by chrkl** [kyma-project/telemetry-manager#292]
**Description**

Fluent Bit is terminated by a SIGSEGV if the configured output is not reachable during the shutdown. 

**Expected result**

Fluent Bit should shut down gracefully. Log chunks that could not be ingested due to the unavailable output are persisted in the filesystem buffer and ingested as soon as the output is functional again.

**Actual result**

Chunk files in the file system buffer end up in a corrupted state and dropped after a restart.

**Steps to reproduce**

- Create a situation where Fluent Bit cannot ingest logs to the configured output
- Restart Fluent Bit
- Logs of new Fluent Bit instance indicate that chunks are corrupted and dropped

**Troubleshooting**

The behaviour is not observed when using the upstream Fluent Bit image (2.1.7). Removing the grafana-loki plugin from the image also solves the issue.

**Comment by a-thaler** [comment]
Not valid anymore as the loki plugin got removed already
