### ISSUE TITLE
Add integration test for Istio tracing

### ISSUE THREAD

**Issue by chrkl** [kyma-project/telemetry-manager#317]
**Description**

The Istio integration test should be extended to validate that a connected trace is produced when a Pod with Istio sidecar receives a request.

**Criteria**
- Deploy an app that produces custom spans
- Verify that custom spans with expected attributes arrive
- Verify that istio spans with expected attributes arrive
- Spans from istio-proxy and app are connected by traceId
- No flakiness of tests
- if feasible: verify istio-ingressgateway spans

**Comment by a-thaler** [comment]
Still missing:
- Verify that custom spans with expected attributes arrive
- Spans from istio-proxy and app are connected by traceId
- Use a public image for the sample app

**Comment by hisarbalik** [comment]
Missing tests

- Validate connection between Istio spans and custom spans
- Validate other span attributes (e.g., k8s resource attribtues)
