### ISSUE TITLE
Service annotation scraping

### ISSUE THREAD

**Issue by chrkl** [kyma-project/telemetry-manager#318]
**Description**

Add support to scrape Prometheus metrics by annotating Kubernetes services with `prometheus.io` annotations.

**Criteria**
- Allow to configure port, scheme and path by annotation
- Behavior is similar to Pod scraping
- Add e2e-test
- Container name should be discovered correctly in the metric attributes
- Remove Prometheus dependency from config builder code

**Comment by skhalash** [comment]
Following a conversation with @chrkl, we've determined that it's not suitable to eliminate targets where the container port isn't specified in the pod spec. We found ourselves choosing between two less-than-ideal paths:

* Drop a target without a specified container port.
* Keep it, risking an incorrect container name attribute if multiple containers exist and the primary container isn't the first on the list.

As defining container ports in a pod spec is optional and frequently omitted, discarding these targets wouldn't be ideal. The second scenario is rarer. However, it's crucial to document this possibility for our users for complete transparency around potential issues.
