### ISSUE TITLE
Enrichment  for absent Service names in Metric and Trace Gateway

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#373]
**Description**
One big advantage of having the centralized gateway approach is that a common enrichment is possible, assuring a certain data quality. The most important attribute is the service name required for doing any correlation between data. Having the service name provided always with the most meaningful value out of the context will assure correlation at any time.

**Criterias**
- A metric or span without a service name should get enriched with a value if the source is known
- The logic should be similar to the Istio behavior by taking the first matching value of:
  - label app.kubernetes.io/name
  - label app
  - deployment name
  - stateful set/daemon set/job name
  - pod name
- If still no meaningful value can be determined, then an "unknown_service"? value should be provided as defined in the OTEL conventions (please double-check)
- Document the feature
- Have regression tests in place

**Reasons**

**Attachments**

See also my investigations at: https://github.com/kyma-project/kyma/issues/17373#issuecomment-1621534183 and https://github.com/kyma-project/kyma/issues/16589

One idea is to use the https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/processor/k8sattributesprocessor#kubernetes-attributes-processor to always enrich the two relevant labels as internal attributes, then in the transformprocessor determine the service name, then drop the two labels again.

**Comment by skhalash** [comment]
According to https://opentelemetry.io/docs/specs/semconv/resource/#service:
> service.name MUST be the same for all instances of horizontally scaled services. If the value was not specified, SDKs MUST fallback to unknown_service: concatenated with [process.executable.name](https://opentelemetry.io/docs/specs/semconv/resource/process/#process), e.g. unknown_service:bash. If process.executable.name is not available, the value MUST be set to unknown_service.

**Comment by skhalash** [comment]
Implemented in https://github.com/kyma-project/telemetry-manager/pull/487
