### ISSUE TITLE
Flaky unittests

### ISSUE THREAD

**Issue by chrkl** [kyma-project/telemetry-manager#378]
**Description**
Telemetry Unittests frequently fail with

```
  [FAILED] Timed out after 10.001s.
  Expected
      <*errors.errorString | 0xc0010f8f60>: 
      did not find the key: missing-secret-ref-logpipeline.conf
      {
          s: "did not find the key: missing-secret-ref-logpipeline.conf",
      }
  to be nil
```

See
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_telemetry-manager/377/pull-telemetry-manager-unit-test/1696551833641684992
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_telemetry-manager/354/pull-telemetry-manager-unit-test/1696423226009194496
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_telemetry-manager/354/pull-telemetry-manager-unit-test/1696416057520033792

**Comment by rakesh-garimella** [comment]
This PR: should fix the issue: https://github.com/kyma-project/telemetry-manager/commit/a3d184ffecf4721ca64fe86cf33985c5b94c506f
