### ISSUE TITLE
Enhance logging for custom Gomega matchers in case of failure

### ISSUE THREAD

**Issue by skhalash** [kyma-project/telemetry-manager#390]
**Description**

Over time, we've built many special Gomega matchers for our e2e tests. You can see them here: [Custom Matchers](https://github.com/kyma-project/telemetry-manager/tree/main/test/testkit/matchers). However, these matchers often lack effective troubleshooting capabilities. When a match fails, it merely returns a false outcome without providing any extra information.

For example, it would be really helpful if `ConsistOfNumberOfLogs(WithAttributeKeys)` could show us exactly which attribute keys are missing in the logs.

Acceptance Criteria

- Look into how we can print more information in Gomega (but not just by using `fmt.Println`).
- Improve Gomega matchers to give us more information when they don't work as expected.

**Reasons**

**Attachments**

**Comment by a-thaler** [comment]
The matchers are already adjusted to print some message always. It is unclear how to improve it further and first we would need a concrete idea to work on that
