### ISSUE TITLE
Improved gateway resource settings

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#409]
**Description**

It was observed that the trace gateway can run OOM under high load where it should stay resiliant. The  setup should be improved to survive high load situations without restarts.

**Criterias**
- under high load the gateway should not crash, instead the memory limiter should kick-in on time to throttle and garbage collect
- same improvements are applied to the metric gateway setup

**Comment by chrkl** [comment]
PR #428 adjusted the resource and memory limiter settings settings to prevent OOMs in the trace-gateway. The otel collector behaves entirely different for metrics. Settings for the metric-gateway have been adjusted with https://github.com/kyma-project/telemetry-manager/pull/419.
