### ISSUE TITLE
Flaky E2E logging tests

### ISSUE THREAD

**Issue by skhalash** [kyma-project/telemetry-manager#441]
**Description**

E2E logging tests are flaky (50% of job runs fail) and often fail for various reasons:
https://status.build.kyma-project.io/?repo=kyma-project%2Ftelemetry-manager&job=*pull-telemetry-manager-e2e-test-logging-release*

**Acceptance Criteria**

* Improve troubleshooting by revamping log matchers (similar to https://github.com/kyma-project/telemetry-manager/pull/437)
* Fix logging e2e tests

**Comment by a-thaler** [comment]
When fixed, please enable the log tests in the gardener integration tests. These are currently not part of the execution in cause of the flakyness
