### ISSUE TITLE
Support running in a denyAll NetworkPolicy environment

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#536]
**Description**
 A security best practice is to deny any network communication by default and enable dedicated channels if needed.
For that, the telemetry module should provide network policies, which enable the required communication channels explicitly.

**Criterias**
- All Integration tests are having a denyAll policy as part of the setup (incl logging and manager related tests)
- Only required ports are listed in the dedicated policies, so no opencensus port on the metric-agent for example
- Everything works as before
- Ingress/Egress traffic not related to users are limited to the relevant parties
- Egress traffic is limited if possible, especially for the operator and the agent

**Reasons**

**Attachments**

https://github.com/kyma-project/telemetry-manager/issues/614

**Comment by chrkl** [comment]
This should already work since our NetworkPolicy to deny pprof is technically an allow policy for everything except pprof. But let's do a test before closing this issue.

**Comment by a-thaler** [comment]
I prefer to have it covered in our test suite by putting a denyAll policy as part of the setup.

Also, the current networkPolicies are not individual per component, we are opening the opencensus port on the metric-agent.. That should be improved.
