### ISSUE TITLE
Reflect metric agent status in metric pipeline status

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#563]
**Description**
At the moment the MetricPipeline status doe reflect only the config and gateway deployment. It ignores the agent fully.

Adjust that by respecting the agent status as well.

Criterias:
- If the agent is not running, the pipeline last condition should be pending
- Agent is incorporated in the status only if at least one relevant input (non-otlp) is activating it
- The module status needs to reflect the new reason as well
- API Documentation is updated
- Relevant tests are written

**Reasons**

**Attachments**

**Comment by hisarbalik** [comment]
Metric pipeline status reflect now also metric agent daemonset when enabled metric agent enabled for metric pipeline, unhealthy metric agent status reflected in the telemetry manager status too.

**Comment by a-thaler** [comment]
We realized that the status cannot be implemented in a meaningful way using the current status convention of the MetricPipeline. We should directly jump into an approach as outlined here: https://github.com/kyma-project/telemetry-manager/issues/601
Will re-open for now till things a re clarified

**Comment by skhalash** [comment]
MetricPipeline status has been redesigned in https://github.com/kyma-project/telemetry-manager/pull/638.
