### ISSUE TITLE
Istio metrics payload has content of agents sidecar

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#606]
**Description**
The istio metric scrape feature is based on a scrape loop discovering all pods having a istio-proxy container. The returned metrics are well defined from resource attribute perspective (so identifying the scraped pod), but the content actually belongs to the sidecar of the agent.

Example metric:
| key |  value
| -- | -- |
| instrumentationScope.name | otelcol/prometheusreceiver
| instrumentationScope.version | 0.89.0
| isMonotonic | true
| kind | SUM
| metric.attributes.connection_security_policy | unknown
| metric.attributes.destination_app | unknown
| metric.attributes.destination_canonical_revision | latest
| metric.attributes.destination_canonical_service | telemetry-metric-gateway
| metric.attributes.destination_cluster | Kubernetes
| metric.attributes.destination_principal | spiffe://cluster.local/ns/kyma-system/sa/telemetry-metric-gateway
| metric.attributes.destination_service | telemetry-otlp-metrics.kyma-system.svc.cluster.local
| metric.attributes.destination_service_name | telemetry-otlp-metrics
| metric.attributes.destination_service_namespace | kyma-system
| metric.attributes.destination_version | unknown
| metric.attributes.destination_workload | telemetry-metric-gateway
| metric.attributes.destination_workload_namespace | kyma-system
| metric.attributes.grpc_response_status | 0
| metric.attributes.reporter | source
| metric.attributes.request_protocol | grpc
| metric.attributes.response_code | 200
| metric.attributes.response_flags | -
| metric.attributes.source_canonical_revision | latest
| metric.attributes.source_canonical_service | telemetry-metric-agent
| metric.attributes.source_cluster | Kubernetes
| metric.attributes.source_principal | spiffe://cluster.local/ns/kyma-system/sa/telemetry-metric-agent
| metric.attributes.source_workload | telemetry-metric-agent
| metric.attributes.source_workload_namespace | kyma-system
| name | istio_requests_total
| resource.attributes.http@scheme | http
| resource.attributes.k8s@cluster@name | api.c-2bb323d.kyma-stage.internal.live.k8s.ondemand.com
| resource.attributes.k8s@container@name | istio-proxy
| resource.attributes.k8s@deployment@name | otel-frontend
| resource.attributes.k8s@namespace@name | example
| resource.attributes.k8s@node@name | ip-10-250-2-95.eu-central-1.compute.internal
| resource.attributes.k8s@pod@name | otel-frontend-86b84cf64d-hsq5q
| resource.attributes.k8s@pod@uid | 1874ef6e-5544-423d-ac82-52d7d4b5bc19
| resource.attributes.k8s@replicaset@name | otel-frontend-86b84cf64d
| resource.attributes.net@host@name | 10.96.1.188
| resource.attributes.net@host@port | 15090
| resource.attributes.service@instance@id | 10.96.1.188:15090
| resource.attributes.service@name | otel-frontend

The istio metric attributes are always the same, only the resource attributes are changing dependent on the scraped pod.

The metric-agent is using an istio sidecar to get istio client certificates injected for scraping custom metrics (not used in this scanario). That sidecar seem to intecept the call to the envoy special port 15090. Comparing the setup to other working solutions reveals an important difference: not all ports should be excluded from outgoing communication but IPRanges, Setting that instead fixes the problem.

Unrelated problem but similar area, please verify if really all incoming ports should be ignored or maybe only the metrics port.

In order to fix the bug, please provide appropriate regression tests.

**Expected result**
The istio metrics are containing the proper metric attributes of the targetted pod

**Actual result**
The istio metrics are containing the metric attributes of the agents sidecar always

**Steps to reproduce**

**Troubleshooting**

**Release Notes**

```

```

**Comment by chrkl** [comment]
The bug has been fixed with PR #609. #662 enhanced the integration test to validate relevant Istio metric attributes.
