### ISSUE TITLE
Filter istio metrics related to telemetry component communication

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#621]
**Description**

Users are interested in the Istio metrics of the business related communication and will accept the cost for storing them. The communication to the telemetry module is not really crucial for the users and will cause a higher volume of data, think of the telemetry-metric-agent scraping a bigger amount of pods.

To be consistent with the trace gateway implementation, all metrics related to telemetry system related communication should be filtered out by default.

**Criteria**
- As a user I will not see any Istio metrics related to communication from/to telemetry components
- As a telemetry module maintainer, I want to avoid unneeded code, so orphaned rules should be removed

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by rakesh-garimella** [comment]
Filters have been implemented in metric agent. Currently following is dropped:
- Metric with source telemetry-metric-agent
- Metric with destination telemetry-metric-gateway
- Metric with destination telemetry-trace-collector
Obsolete filter ruless have been dropped in trace collector
