### ISSUE TITLE
Metric endpoint defined in module status

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#622]
**Description**
The trace endpoint is already available in the module status. As the metrics feature was not part of the official release yet, the endpoint data was not added yet. That should be done now

**Criteria**
- As a user I need to know where to push metrics to and will find that info in the module status

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by hisarbalik** [comment]
Telemetry module status will reflect available metric pipeline endpoint, telemetry module busola extension configured to show the metric pipeline endpoints in the detail view of telemetry module
