### ISSUE TITLE
Have the metrics features as part of the regular release

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#623]
**Description**
It is time to release the new metrics feature. So do all prep works required for that.

**Criteria**
- A regular release contains all relevant resources to have the metrics feature usable
- The metrics feature is enabled by default
- The experimental release flow stays but will have the same effect as the regular release
- Remove any "experimental" comment from the docu pages
- Add a new Github action for executing metrics test for releases
- Remove the feature flags for metrics and traces and logs and modules
- Assure that module reconcilation can be still disabled via the override mechanism

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by shorim** [comment]
All of the acceptance criteria are tackled in this [PR](https://github.com/kyma-project/telemetry-manager/pull/629) except the last one `Assure that module reconcilation can be still disabled via the override mechanism`. It will be tackled in a different PR as it is not strongly related to including the metrics feature in the fast and regular releases.

**Comment by shorim** [comment]
The disabling of the module reconciliation via the override ConfigMap is done in this [PR](https://github.com/kyma-project/telemetry-manager/pull/643)
