### ISSUE TITLE
Rename telemetry-operator to telemetry-manager

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#651]
**Description**
To follow the module guidelines, the manager deployment should be named manager. The repository name and even parts of the documentation are using that term as the renaming should happen as soon as the modularization of the component is finished.

**Criterias**
- The deployment and related resources are renamed
- There is no evidence of "telemetry-operator" in any resource
- The documentation is not using the "operator" term anymore, incl. diagrams
- Indicate migration procedure as part of Release notes

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by hisarbalik** [comment]
The Telemetry operator is renamed with all related resources to the manager. Tested on gardener cluster manually and tested on a k3d cluster with lifecycle manager. Upgrade from module release 1.9 on k3d cluster with lifecycle manager work also without any side effect, all resources from the previous module version 1.9 with name operator successfully cleaned up after upgrade.
