### ISSUE TITLE
LogPipeline Status indicates problems with client cert

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#653]
**Description**
If an invalid cert file gets configured for a logpipeline, fluentbit falls into a crashloop. Validation logic should assure that no config gets generated if the cert is invalid in an obvious way and the status is reflected nicely in the pipeline status. Especially an expired cert should be detected very easy.
Additionally, a certificate which is about to expire (2 weeks?) should be indicated in the status as well.

**Criterias**
- As a user I will get feedback via the LogPipeline status if a invalid cert/key/ca is supplied
- As an operator, I will not get notified about crashloops if an invalid cert/key/ca gets supplied
- At least parsing, decoding and the expiry should be verified
- As a user I get warned about a cert which is about to expire but all is running healthy till then (use a positive condition with a specialized reason)

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by hisarbalik** [comment]
- Add TLS certificate validation
- Add new reasons `InvalidTLSCert` for condition type `ConfigurationGenerated`
- Add new reasons `InvalidTLSPrivateKey` for condition type `ConfigurationGenerated`
- Add new reasons `ExpiredTLSCert` for condition type `ConfigurationGenerated`
- Add new reasons `TLSCertAboutToExpire` for condition type `ConfigurationGenerated` when the configured certificate expires in two weeks
- LogPipeline configuration generation will skipped when the certificate is invalid or expired
- Module should show a `Warning` state when any LogPipeline has a certificate that will expire in two weeks
