### ISSUE TITLE
Bump Fluent Bit to 2.2.1

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#673]
**Description**
FluentBit 2.2.1 got released with important library updates. The rollout of FluentBit 2.2.0 was stopped as an important metric on the tail input was zeroed, that should be fixed as well.
Also, we should take the chance and finally get rid of the sequential_http plugin, please wipe it out as it is not in use anymore.

**Criterias**
- Fluentbit is updated to 2.2.1 (or update is topped because of serious findings which are documented here)
- All metrics are working as expected
- No performance degredations
- Integration tests are working

**Comment by skhalash** [comment]
The issue with the input metric https://github.com/fluent/fluent-bit/issues/8287 is indeed fixed in 2.2.1

**Comment by skhalash** [comment]
No significant difference in resource consumption was found compared to 2.10.1

**Comment by skhalash** [comment]
⚠️ Since we do not build sequential_http custom plugin anymore, the dryrun command had to be adapted
