### ISSUE TITLE
Manual Perf test for tracing

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#692]
**Description**

When making crucial changes to the data processing or updating the otel-collector version, a performance degradation or increased resource consumption could be the consequence. For now these changes were tested in a undocumented manual way. That way needs to be improved by having it formulized, repeatable and transparent.

Goal: Document what to execute when a new version of the otel-collector is tested or crucial changes in the pipeline are introduced

- Have clear instructions on
  - how to prepare the setup using strict pre-requisites on the setup (fixed amount of nodes etc)
  - how to test the documented max throughput (assuring that resource consumption is still fitting)
  - how to test the same with three pipelines
- Have a place to record resulting KPIs for every change in the contributors section
- Have future automation in mind: one command to execute it all  providing some config
- Have first records available as a baseline

**Reasons**
Detect degradations before rollout by having quality gates in place for performance testing

**Attachments**

**Release Notes**

```

```

**Comment by hisarbalik** [comment]
- User documentation added, docs are defining prerequisites for test execution and predefined test cases. 
- Predefined test components added
- Test run scripts added (single command, deploy, execute and fetch results)

**Comment by a-thaler** [comment]
Could you please add standard error handling flags to the script to assure a certain level of quality:
```
# standard bash error handling
set -o nounset  # treat unset variables as an error and exit immediately.
set -o errexit  # exit immediately when a command fails.
set -E          # needs to be set if we want the ERR trap
set -o pipefail # prevents errors in a pipeline from being masked
```
