### ISSUE TITLE
Manual Perf test for metrics

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#738]
**Description**

Goal: Document what to execute when a new version of the otel-collector is tested or crucial changes in the pipeline are introduced in regards to metrics

- Have clear instructions on
  - how to prepare the setup using strict pre-requisites on the setup (fixed amount of nodes etc)
  - how to test the documented max throughput (assuring that resource consumption is still fitting)
  - how to test the same with three pipelines
  - how to test the scraping part
- Have a place to record resulting KPIs for every change in the contributors section
- Have future automation in mind: one command to execute it all  providing some config
- Have first records available as a baseline
- Assure that new records can be added easily and compared
- Assure that we get one test suite experience

**Reasons**
Detect degradations before rollout by having quality gates in place for performance testing

**Attachments**

**Release Notes**

```

```

**Comment by hisarbalik** [comment]
- All load test docs and scripts merged to the single document and moved to the docs/contributor/telemetry-load-test
- Metric Gateway and Metric Agent test scripts are implemented
- Test result for version 0.92 documented for both Metric Gateway and Metric Agent
- All test (inkl. Trace Gateway) integrated in a single test suite
