### ISSUE TITLE
Simplify Makefile

### ISSUE THREAD

**Issue by skhalash** [kyma-project/telemetry-manager#740]
**Description**

We began the project with a Kubebuilder-scaffolded Makefile. While it served its purpose initially, we found ourselves adding more to it, leading to a bloated structure. There's a notable amount of duplicated commands, especially in running e2e tests. Simplifying and improving it is now a priority:
* Compare your Makefile with the latest Kubebuilder version for improvements.
* Analyze other Kyma teams' Makefiles for patterns and best practices.
* Review Makefiles from open-source Kubebuilder projects.
* Follow Makefile best practices for Go projects:
    * Separate concerns into distinct targets (e.g., build, test, e2e).
    * Consider parameterizing targets for flexibility.
    * Apply the DRY principle to eliminate duplication.
* Create an Architecture Decision Record (ADR) document for Makefile changes.

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by TeodorSAP** [comment]
Work in progress...
![MakefileArchitecture](https://github.com/kyma-project/telemetry-manager/assets/103431261/203eba2e-1991-43e2-acff-a2493197e7b1)

**Comment by TeodorSAP** [comment]
This is how the dependency graph looks like currently:
![MakefileDependency](https://github.com/kyma-project/telemetry-manager/assets/103431261/4a9d2ab9-c737-4cbd-aef3-7b3f452996c1)

**Comment by TeodorSAP** [comment]
New and updated Makefile architecture:
![Misc - SAP, TM_ Makefile Simplification (1)](https://github.com/kyma-project/telemetry-manager/assets/103431261/fa80c7ec-980d-48ec-bd3b-287fa8828a27)

**Comment by TeodorSAP** [comment]
And this is how the new Makefile targets dependency graph looks like:
|<img width="562" alt="Screenshot 2024-02-28 at 15 19 34" src="https://github.com/kyma-project/telemetry-manager/assets/103431261/fc327cd5-ce49-4c50-b278-cc04b56c1c4c">|<img width="388" alt="Screenshot 2024-02-28 at 15 20 32" src="https://github.com/kyma-project/telemetry-manager/assets/103431261/64397d60-d665-4e86-a468-02464a355208">|<img width="353" alt="Screenshot 2024-02-28 at 15 22 56" src="https://github.com/kyma-project/telemetry-manager/assets/103431261/28fd240d-e52d-4567-bdd8-ae50ec10d329">|
|:-:|:-:|:-:|
|Makefile|provision.mk|dependencies.mk|
