### ISSUE TITLE
Manual Perf test for logs

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#765]
**Description**

This is a follow-up of https://github.com/kyma-project/telemetry-manager/issues/738

Goal: Document what to execute when a new version of fluentbit is tested or crucial changes in the pipeline are introduced in regards to logs. Unify the testing approach with the [exiting setup](https://github.com/kyma-project/telemetry-manager/tree/main/docs/contributor/telemetry-load-test)

- Have clear instructions on
  - how to prepare the setup using strict pre-requisites on the setup (fixed amount of nodes etc)
  - how to test the documented max throughput (assuring that resource consumption is still fitting)
  - how to test the same with three pipelines
  - how to test the tail part
- Have a place to record resulting KPIs for every change in the contributors section
- Have future automation in mind: one command to execute it all  providing some config
- Have first records available as a baseline
- Assure that new records can be added easily and compared
- Assure that we get one test suite experience
- Update to flluentbit to 2.2.2 is performed as part of the story

**Reasons**
Detect degradations before rollout by having quality gates in place for performance testing

**Attachments**

**Release Notes**

```

```

**Comment by hisarbalik** [comment]
Similar to the Trace and MetricPipeline tests
- LogPipeline test target added to the existing script
- Predefined test setup added
- Fluent-Bit version 2.2.1 and 2.2.2 has been tested and results documented
