### ISSUE TITLE
Introduce GOMEMLIMIT and new resource limit configurations to all components

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#804]
As a result of https://github.com/kyma-project/telemetry-manager/issues/771 we identified that setting the GOMEMLIMIT will only have positive effects and should be done for all of the components we are running

**Criterias**
- All components are having the GOMEMLIMIT setting applied
  - trace-gateway
  - metric-gateway
  - metric-agent
  - telemetry-manager
  - self-monitor
- All components have a validated resource footprint
- Adjust otel-collector settings to leverage queue in the backpressure scenario
- Document decision criterias for performce test results, add comment column in case you continue with numbers which are violating criterias

**Tasks**
- Apply GOMEMLIMIT to the Trace and Metric gateway and metric agent based on findings from docs/contributor/pocs/gomemlimit-telemetry-memory.md
- Setup new resource limits for Trace gateway similar to the Metric gateway
- Setup and test new memory limiter configuration based on new GOMEMLIMIT configuration to allow less aggressive memory limiter
- Apply GOMEMLIMIT to the telemetry-operator and the system log collector setup

**Comment by hisarbalik** [comment]
- GOMEMLIMIT environment variable and as value %80 of memory limit of trace gateway, metric gateway, metric agent, telemetry module, and self-monitor added
- Trace gateway, metric gateway, and metric agent `memory_limiter` processor configuration updated accordingly new GOMEMLIMIT configuration
- New load test results added with GOMEMLIMIT configuration
