### ISSUE TITLE
Remove Undeploy operator deployment step from manage-upgrade Job

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/telemetry-manager#813]
Upgrade Job failing because of resource name changes, old resources after upgrade not removed automatically a workaround added to the `manager upgrade job` and have to be reverted after next release.
 
After the next release, modify the following steps from pr-lifecycle.yml:

Modify step at line 39

```
    - name: Wait for operator readiness
      shell: bash
      run: kubectl -n kyma-system rollout status deployment telemetry-operator --timeout=90s
```

to

```
    - name: Wait for manager readiness
      shell: bash
      run: kubectl -n kyma-system rollout status deployment telemetry-manager --timeout=90s
```

Remove step from line 68

```
    - name: Undeploy operator deployment
      shell: bash
      run: | 
        kubectl -n kyma-system scale deployment telemetry-operator --replicas 0
```

**Comment by chrkl** [comment]
Listed changes have been applied by PR #827.
