### ISSUE TITLE
Report self-monitor alerts to the pipeline status

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#822]
**Description**
The next step in getting https://github.com/kyma-project/telemetry-manager/issues/425 realized is to leverage the newly deployed prometheus to enrich the status of pipelines and the module.

As a follow-up, a proper priority-class should be set as well

**Criterias**
- Prometheus is collecting the relevant metrics (see https://github.com/kyma-project/telemetry-manager/pull/802)
- Prometheus is having the relevant alertrules (see https://github.com/kyma-project/telemetry-manager/pull/802)
- The pipeline controllers are querying prometheus (if available) for alerts and report to the pipeline status
- Cover with unit tests
- Data flow condition might be presented as "UNKNOWN" if prometheus is not there.
- A priority class gets configured analogue to all other components

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by skhalash** [comment]
- [ ] RBAC: restrict to kyma-system
- [ ] PriorityClass
- [ ] Scrape config
- [ ] Dummy alert setup
- [ ] Alerts from the ADR
- [ ] Wrap Prometheus client -> status update
