### ISSUE TITLE
Fix and review cpu utilization metrics

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#838]
**Description**

It turns out that the utilization metrics currently exposed by the kubeletstatsreceiver are calculated wrong and with that also are wrongly named, see https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27885

With https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/25901 a new metric is available having the proper name and calculation. The new metric is still disabled by default and the old metric enabled, but the old metrics have already a deprecation warning:

```
{"level":"warn","ts":1709053389.6699765,"caller":"metadata/generated_metrics.go:2894","msg":"[WARNING] `container.cpu.utilization` should not be enabled: WARNING: This metric will be disabled in a future release. Use metric container.cpu.usage instead.","kind":"receiver","name":"kubeletstats","data_type":"metrics"}
{"level":"warn","ts":1709053389.6699817,"caller":"metadata/generated_metrics.go:2897","msg":"[WARNING] `k8s.node.cpu.utilization` should not be enabled: WARNING: This metric will be disabled in a future release. Use metric k8s.node.cpu.usage instead.","kind":"receiver","name":"kubeletstats","data_type":"metrics"}
{"level":"warn","ts":1709053389.6699867,"caller":"metadata/generated_metrics.go:2900","msg":"[WARNING] `k8s.pod.cpu.utilization` should not be enabled: This metric will be disabled in a future release. Use metric k8s.pod.cpu.usage instead.","kind":"receiver","name":"kubeletstats","data_type":"metrics"}
```

**Goal**
- Switch to the new metrics and update the Cloud Logging dashboards
- Review new metrics available https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/24905

**Criterias**
- The new metrics are enabled and used in the Cloud Logging dashboards
- The old metrics are disabled by default
- If a specific annotation is present on the module CR, the old metric will stay enabled (additionally to the new metric). If people migrated, they can just delete the annotation.

https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/27885

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by hisarbalik** [comment]
- Configuration capability for `kubeletstatreceiver` to enable or disable metrics added 
- Deprecated *.cpu.utilization disabled
- New metrics *.cpu.usage enabled
- Unit and e2e test are updated accordingly new configuration changes
