### ISSUE TITLE
Advanced status feature on development release with custom image for self-monitor

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#871]
**Description**
A first MVP got established for https://github.com/kyma-project/telemetry-manager/issues/425. Now it is time to make it accessable by bundling it as part of the development release. For that the used prometheus image must be located in the kyma registry, so it is a good point in time to switch to a custom image to reduce the amount of dependencies inside the image.

**Criterias**
- The advanced status feature is accessible via the development release (only)
- The used self-monitor image is a hardened prometheus image located in the kyma registry. Details on stripping down the prometheus plugins can be found here: https://github.com/kyma-project/telemetry-manager/issues/770.
- Have an e2e test assuring a successful setup of the self-monitor and a healthy telemetry flow for metric and trace pipeline types
- The new image is included in security scans and is following security best practices

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by rakesh-garimella** [comment]
- Custom docker image has been created [here](https://github.com/kyma-project/third-party-images/pull/421)
- The e2e test has been added [here](https://github.com/kyma-project/telemetry-manager/pull/915)
