### ISSUE TITLE
Have a first OTLP output available in the development release of a LogPipeline which activates a Log gateway

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#872]
**Description**
Relates to https://github.com/kyma-project/telemetry-manager/issues/556 and https://github.com/kyma-project/telemetry-manager/issues/1415
To kick-start the OTLP based log feature, an OTLP output should be supported in the same way as for other pipelines, so that a log gateway gets established and be used for custom log pushs

**Criterias**
- An OTLP output requires an OTLP input for now
- The activation of the OTLP output will spin up a Log Gateway
- The new log OTLP endpoints are documented in the module CR status
- You can push log data to the gateway
- The gateway will have the typical OTLP receiver and export via OTLP as deined in the OTLP output section
- Disabling all otlp outputs will remove the log gateway

**Comment by a-thaler** [comment]
Preparation steps:
- Have only the spec in the spec folders (struct definitions)
- Logic is moved out into well-defined packages and is being used across API versions

**Comment by TeodorSAP** [comment]
This refactoring is needed, before moving forward:
https://github.com/kyma-project/telemetry-manager/issues/1644
