### ISSUE TITLE
 Remove loki output

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#873]
**Description**

As follow up of the disabled loki output (https://github.com/kyma-project/telemetry-manager/issues/461), the output should get removed finally. The API was not usable for nearly one year and not documented anywhere, so it can be safely removed.

**Criterias**
- Verify that there is no cluster using the output
- There is no loki output in the alpha and beta version available
- No occurence of the API is available in the docu, code, tests
- Validation/reason is cleaned up

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by hisarbalik** [comment]
- The grafana-loki output removed from both versions of LogPipeline removed
- The test and validation code related to the grafana-loki removed
- The grafana-loki output was removed from documents and examples
- All customer clusters from all environments checked for the existence of LogPipelines with grafana-loki output, and no occurrence was found
