### ISSUE TITLE
Support for fluentbit in advanced status handling

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#917]
**Description**
As part of https://github.com/kyma-project/telemetry-manager/issues/425 support for the advanced status  for the log component is needed as well. That should be realized on base of https://github.com/kyma-project/telemetry-manager/issues/904

**Criterias**
- Overall: The user can see data flow problems in the status of a LogPipeline and Module CR
- Self-Monitor is collecting relevant metrics for fluentbit outlined in [concept](https://github.com/kyma-project/telemetry-manager/issues/904)
- Self-Monitor defines alerts on base of metrics as outlined in [concept](https://github.com/kyma-project/telemetry-manager/issues/904)
- Manager is enriching LogPipeline and Module status based on new alerts
- Manager webhook gets triggered on new alerts
- Have basic e2e tests
- New status is documented

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by skhalash** [comment]
TODO
- [ ] Reflect LogPipeline flow health in Telemetry
- [ ] Add a basic test
- [ ] Docs
- [ ] Status condition order after an upgrade

To discuss with the team:
- [ ] Flow health if no config is generated
- [ ] Custom output matching problem
