### ISSUE TITLE
Full test coverage for advanced status

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#919]
**Description**

Before https://github.com/kyma-project/telemetry-manager/issues/425 can get finalized, the full feature must be covered by e2e tests. That mainly includes triggering every condition reason by a test setup.

**Criterias**
- All reasons of the new condition are tested

**Actions**
- [x] Come up with a concept on how to test the feature. It is hard to test all situations. Maybe a contract test based on metrics is enough?
- [x] Implement tests for logs
- [ ] Implement tests for traces
- [ ] Implement tests for metrics

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by skhalash** [comment]
In general, we want to test how OTel Collector and Fluent Bit instrumentation logic works. Contract based testing using mocks is not enough, we need the actual software running and negative scenarios simulated.
