### ISSUE TITLE
Self-Monitor monitoring

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#920]
**Description**

The new self-monitor integration of https://github.com/kyma-project/telemetry-manager/issues/42 needs to be observable in order to operate it.

**Criterias**
- Assure that manager exposes metrics about communication to the self-monitor
- Have operational setup for SAP managed offering

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by skhalash** [comment]
The new metrics will be rolled out in 1.16
