### ISSUE TITLE
Concept on how to collect module status metrics

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#921]
**Description**
As part of https://github.com/kyma-project/telemetry-manager/issues/728 a new metric input should be stablished which supports collecting the status of all modules and the kyma cr itself.
For that a technology needs to be determined to collect the data from the APIServer and convert them into metrics

**Criterias**
- Have a document written
  - which compares feasible solutions and proposes a concrete one
  - it defines the decision criterias for the proposal
  - a proof of feasability might be done in a later step
  - have a contrete API proposal
- Conditions for the evaluation
  - The metrics needs to follow the OTEL semantic conventions
  - The conditions and reasons should get collected dynamically, without a manual listing
  - The modules should get determined dynamically

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by chrkl** [comment]
A concept has been documented with PR #995.
