### ISSUE TITLE
Certificate validation for Traces and Metrics

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#930]
**Description**
If an invalid cert file gets configured for a trace or metricpipeline, otel-collector falls into a crashloop. Validation logic should assure that no config gets generated if the cert is invalid in an obvious way and the status is reflected nicely in the pipeline status. Especially an expired cert should be detected very easy.
Additionally, a certificate which is about to expire (2 weeks?) should be indicated in the status as well.

**Criterias**
- As a user I will get feedback via the Trace/MetricPipeline status if a invalid cert/key/ca is supplied
- As an operator, I will not get notified about crashloops if an invalid cert/key/ca gets supplied
- At least parsing, decoding and the expiry should be verified
- As a user I get warned about a cert which is about to expire but all is running healthy till then (use a positive condition with a specialized reason)

See also https://github.com/kyma-project/telemetry-manager/issues/653

**Reasons**

**Attachments**

**Release Notes**

```

```

**Comment by a-thaler** [comment]
Still todo:
- Unit test coverage
- E2E test coverage
- Document new status
- Do not override Invalid status with any other status in module CR

**Comment by rakesh-garimella** [comment]
TLS validation for metrics and traces has been implemented. The status is also shown in the telemetry CR.
