### ISSUE TITLE
Review and Update Telemetry-related content in Kyma Learning Journey

### ISSUE THREAD

**Issue by mmitoraj** [kyma-project/telemetry-manager#957]
**Description**

[Delivering Side-by-Side Extensibility based on SAP BTP, Kyma runtime](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime) Kyma Learning Journey got outdated. Markus Haug would like to cooperate with us in updating it.

For the Telemetry module, we need to take care of the following items:

- [x] [Describing Observability in Kyma](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/describing-observability-in-kyma_d36f9eea-f485-47b0-aab7-af1bd1be6e76). -> Needs major refactoring by removing the first part and focus on explaining the new strategy. Probably should be done in combination with the integration to Cloud Logging as a ready-to-use backend solution
- [x] [Monitoring extensions with custom metrics in Kyma](https://learning.sap.com/learning-journeys/deliver-side-by-side-extensibility-based-on-sap-btp-kyma-runtime/monitoring-extensions-with-custom-metrics-in-kyma_f98595fe-24b5-46ce-a928-2f52394123cc) -> Needs major refactoring by not relying on the in-cluster stack but indeed using Cloud Logging as backend

**Reasons**

Content update requiring cross-team collaboration.

**Attachments**

See #5292 in internal /backlog

**Comment by NHingerl** [comment]
We've got a PR for this in the respective repo; just need to find time for reviewing it.

**Comment by a-thaler** [comment]
First draft is ready for general feedback: https://github.tools.sap/SAP-BTP-Courses/KYM400_Content/pull/43

**Comment by a-thaler** [comment]
I updated the example to fit to the new and the old exercise.
I updated the deployment manifests to use the new Unit number (https://github.com/SAP-samples/kyma-runtime-learning-journey/pull/3)
I updated the course content with https://github.tools.sap/SAP-BTP-Courses/KYM400_Content/pull/43

**Comment by a-thaler** [comment]
New content is provided and will be taken over, closing the ticket already
