### ISSUE TITLE
Have well-defined instrumentationScope for metrics potentially replacing kyma.source attribute

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/telemetry-manager#973]
**Description**

The metrics resulting from MetricPipeline inputs currently have an instrumentationScope defined which seems not well-defined, derived from the otel-collector binary name in combination with the used receiver, like "otelcol/prometheusreceiver".

The instrumentationScope is a a useful attribute to discover metrics and have a first drill-down to find a specific metric. Hereby, it is very helpful to also narrow down the metrics collected by the MetricPipeline by input type. That currently is possible by using the mentioned scopes already, however, the naming is not very good and should be improved.

Also, when having an aligned name, it might even replace the internal resource attribute "kyma.source" which targets a similar goal. Using the instrumentationScope instead will have the advantage of simplifying the setup.

**Goal**
- Use well-defined instrumentationScopes usable by users for metric discovery
- Reduce complexity by dropping the kyma.source attribute

**Criterias**
- The instrumentationScope of all metrics emmitted by telemetry inputs are meaningful and relatable to the input name, for example a value like "io.kyma-project.telemetry/prometheus" (please validate with otel semantic conventions and usage examples on how to name it)
- The attributes are part of the telemetry contract and are tested in an automated way to assure compatibility
- Additional enrichment and removal of a kyma.source attribute is not part of an otel-collector config

**Reasons**

**Attachments**

The instrumentationScope.version attribute will be enriched with that story: https://github.com/kyma-project/telemetry-manager/issues/1000

**Release Notes**

```

```

**Comment by rakesh-garimella** [comment]
The instrumentation scope has been implemented
- `io.kyma-project.telemetry/prometheus` -> for prometheus metrics
- `io.kyma-project.telemetry/istio` -> for istio metrics
- `io.kyma-project.telemetry/runtime` -> for kubestat metrics
- removed `kyma.source` from agent and gateway
